INSERT INTO chords (name,  spelling,  chord_chart)
VALUES ('A#',  'A#, CX, E#', '/static/Asharp.png'), 
       ('A#5',  'A#, E#, A#', '/static/Asharp5.png'), 
       ('A#7',  'A#, CX, E#, G#', '/static/Asharp7.png'), 
       ('A#add9',  'A#, CX, E#, B#', '/static/Asharpadd9.png'), 
       ('A#dim',  'A#, C#, E', '/static/Asharpdim.png'), 
       ('A#dim7',  'A#, C#, E, G', '/static/Asharpdim7.png'), 
       ('A#m',  'A#, C#, E#', '/static/Asharpm.png'), 
       ('A#m7',  'A#, C#, E#, G#', '/static/Asharpm7.png'), 
       ('A#maj7',  'A#, CX, E#, GX', '/static/Asharpmaj7.png'), 
       ('A#sus4',  'A#, D#, E#  G#', '/static/Asharpsus4.png'), 
       ('Bb',  'B♭, D, F', '/static/Asharp.png'), 
       ('Bb5',  'B♭, F, B♭', '/static/Asharp5.png'), 
       ('Bb7',  'B♭, D, F, A♭', '/static/Asharp7.png'), 
       ('Bbadd9',  'B♭, D, F, C', '/static/Asharpadd9.png'), 
       ('Bbdim',  'B♭, D♭, F♭', '/static/Asharpdim.png'), 
       ('Bbdim7',  'B♭, D♭, F♭, A♭♭', '/static/Asharpdim7.png'), 
       ('Bbm',  'B♭, D♭, F', '/static/Asharpm.png'), 
       ('Bbm7',  'B♭, D♭, F', '/static/Asharpm7.png'), 
       ('Bbmaj7',  'B♭, D, F, A', '/static/Asharpmaj7.png'), 
       ('Bbsus4',  'B♭, E♭, F', '/static/Asharpsus4.png'), 
       ('A',  'A, C#, E', '/static/A.png'), 
       ('A5',  'A, E, A', '/static/A5.png'), 
       ('A7',  'A, C#, E, G', '/static/A7.png'), 
       ('Aadd9',  'A, C#, E, B', '/static/Aadd9.png'), 
       ('Adim',  'A, C, E♭', '/static/Adim.png'), 
       ('Adim7',  'A, C, E♭, G♭', '/static/Adim7.png'), 
       ('Am',  'A, C, E', '/static/Am.png'), 
       ('Am7',  'A, C, E, G', '/static/Am7.png'), 
       ('Ama7',  'A, C#, E, G#', '/static/Amaj7.png'), 
       ('Asus4',  'A, D, E', '/static/Asus4.png'), 
       ('B',  'B, D#, F#', '/static/B.png'),
       ('B5',  'B, F#, B', '/static/B5.png'),
       ('B7',  'B, D#, F#, A', '/static/B7.png'),
       ('Badd9',  'B, D#, F#, C#', '/static/Badd9.png'),
       ('Bdim',  'B, D, F', '/static/Bdim.png'),
       ('Bdim7',  'B, D, F, Ab', '/static/Bdim7.png'),
       ('Bm',  'B, D, F#', '/static/Bm.png'),
       ('Bm7',  'B, D, F#, A', '/static/Bm7.png'),
       ('Bmaj7',  'B, D#, F#, A#', '/static/Bmaj7.png'),
       ('Bsus4',  'B, E, F#', '/static/Bsus4.png'),
       ('C#',  'C#, E#, G#', '/static/Csharp.png'),
       ('C#5',  'C#, E#, C#', '/static/Csharp5.png'),
       ('C#7',  'C#, E#, G#, B', '/static/Csharp7.png'),
       ('C#add9',  'C#, E#, G#, D#', '/static/Csharpadd9.png'),
       ('C#dim',  'C#, E, G', '/static/Csharpdim.png'),
       ('C#dim7',  'C#, E, G, B♭', '/static/Csharpdim7.png'),
       ('C#m',  'C#, E, G#', '/static/Csharpm.png'),
       ('C#m7',  'C#, E, G#, B', '/static/Csharpm7.png'),
       ('C#maj7',  'C#, E#, G#, B#', '/static/Csharpmaj7.png'),
       ('C#sus4',  'C#, F#, G#', '/static/Csharpsus4.png'),
       ('Db',  'C#, E#, G#', '/static/Csharp.png'),
       ('Db5',  'D♭, A♭, D♭', '/static/Csharp5.png'),
       ('Db7',  'D♭, F, A♭, C♭', '/static/Csharp7.png'),
       ('Dbadd9',  'D♭, F, A♭, E♭', '/static/Csharpadd9.png'),
       ('Dbdim',  'D♭, F♭, A♭♭', '/static/Csharpdim.png'),
       ('Dbdim7',  'D♭, F♭, A♭♭, C♭♭', '/static/Csharpdim7.png'),
       ('Dbm',  'D♭, F♭, A♭', '/static/Csharpm.png'),
       ('Dbm7',  'D♭, F♭, A♭, C♭', '/static/Csharpm7.png'),
       ('Dbmaj7',  'D♭, F, A♭, C', '/static/Csharpmaj7.png'),
       ('Dbsus4',  'D♭, G♭, A♭', '/static/Csharpsus4.png'),
       ('C',  'C, E, G', '/static/C.png'),
       ('C5',  'C, E, C', '/static/C5.png'),
       ('C7',  'C, E, G, B♭', '/static/C7.png'),
       ('Cadd9',  'C, E, G, D', '/static/Cadd9.png'),
       ('Cdim',  'C, E♭, G♭', '/static/Cdim.png'),
       ('Cdim7',  'C, E♭, G♭, B♭♭', '/static/Cdim7.png'),
       ('Cm',  'C, E♭, G', '/static/Cm.png'),
       ('Cm7',  'C, E♭, G, B♭', '/static/Cm7.png'),
       ('Cmaj7',  'C, E, G, B', '/static/Cmaj7.png'),
       ('Csus4',  'C, F, G', '/static/Csus4.png'),
       ('D#', 'D#, FX, A#', '/static/Dsharp.png'),
       ('D#5', 'D#, A#, D#', '/static/Dsharp5.png'),
       ('D#7', 'D#, FX, A#, C#', '/static/Dsharp7.png'),
       ('D#add9', 'D#, FX, A#, E#', '/static/Dsharpadd9.png'),
       ('D#dim', 'D#, F#, A', '/static/Dsharpdim.png'),
       ('D#dim7', 'D#, F#, A, C', '/static/Dsharpdim7.png'),
       ('D#m', 'D#, F#, A#', '/static/Dsharpm.png'),
       ('D#m7', 'D#, F#, A#, C#', '/static/Dsharpm7.png'),
       ('D#maj7', 'D#, FX, A#, CX', '/static/Dsharpmaj7.png'),
       ('D#sus4', 'D#, G#, A#', '/static/Dsharpsus4.png'),
       ('Eb', 'E♭, G, B♭', '/static/Dsharp.png'),
       ('Eb5', 'E♭, B♭, E♭', '/static/Dsharp5.png'),
       ('Eb7', 'E♭, G, B♭, D♭', '/static/Dsharp7.png'),
       ('Ebadd9', 'E♭, G, B♭, F', '/static/Dsharpadd9.png'),
       ('Ebdim', 'E♭, G♭, B♭♭', '/static/Dsharpdim.png'),
       ('Ebdim7', 'E♭, G♭, B♭♭, D♭♭', '/static/Dsharpdim7.png'),
       ('Ebm', 'E♭, G♭, B♭', '/static/Dsharpm.png'),
       ('Ebm7', 'E♭, G♭, B♭, D♭', '/static/Dsharpm7.png'),
       ('Ebmaj7', 'E♭, G, B♭, D', '/static/Dsharpmaj7.png'),
       ('Ebsus4', 'E♭, G, B♭, D', '/static/Dsharpsus4.png'),
       ('D', 'D, F#, A', '/static/D.png'),
       ('D5', 'D, A, D', '/static/D5.png'),
       ('D7', 'D, F#, A, C#', '/static/D7.png'),
       ('Dadd9', 'D, F#, A, E', '/static/Dadd9.png'),
       ('Ddim', 'D, F, A♭', '/static/Ddim.png'),
       ('Ddim7', 'D, F, A♭, C♭', '/static/Ddim7.png'),
       ('Dm', 'D, F, A', '/static/Dm.png'),
       ('Dm7', 'D, F, A, C', '/static/Dm7.png'),
       ('Dmaj7', 'D, F#, A, C#', '/static/Dmaj7.png'),
       ('Dsus4', 'D, G, A', '/static/Dsus4.png'),
       ('E', 'E, G#, B', '/static/E.png'),
       ('E5', 'E, B, E', '/static/E5.png'),
       ('E7', 'E, G#, B, D', '/static/E7.png'),
       ('Eadd9', 'E, G#, B, F#', '/static/Eadd9.png'),
       ('Edim', 'E, G, B♭', '/static/Edim.png'),
       ('Edim7', 'E, G, B♭, D♭', '/static/Edim7.png'),
       ('Em', 'E, G, B', '/static/Em.png'),
       ('Em7', 'E, G, B, D', '/static/Em7.png'),
       ('Emaj7', 'E, G#, B, D#', '/static/Emaj7.png'),
       ('Esus4', 'E, A, B', '/static/Esus4.png'),
       ('F#', 'F#, A#, C#', '/static/Fsharp.png'),
       ('F#5', 'F#, C#, F#', '/static/Fsharp5.png'),
       ('F#7', 'F#, A#, C#, E', '/static/Fsharp7.png'),
       ('F#add9', 'F#, A#, C#, G#', '/static/Fsharpadd9.png'),
       ('F#dim', 'F#, A, C', '/static/Fsharp.png'),
       ('F#dim7', 'F#, A, C, E♭', '/static/Fsharp.png'),
       ('F#m', 'F#, A, C#', '/static/Fsharpm.png'),
       ('F#m7', 'F#, A, C#, ', '/static/Fsharpm7.png'),
       ('F#maj7', 'F#, A#, C#, E#', '/static/Fsharpmaj7.png'),
       ('F#sus4', 'F#, B, C#', '/static/Fsharpsus4.png'),
       ('Gb', 'G♭, B♭, D♭', '/static/Fsharp.png'),
       ('Gb5', 'G♭, D♭, G♭', '/static/Fsharp5.png'),
       ('Gb7', 'G♭, B♭, D♭, F♭', '/static/Fsharp7.png'),
       ('Gbadd9', 'G♭, B♭, D♭, A♭', '/static/Fsharpadd9.png'),
       ('Gbdim', 'G♭, B♭♭, D♭♭', '/static/Fsharp.png'),
       ('Gbdim7', 'G♭, B♭, D♭, F', '/static/Fsharp.png'),
       ('Gbm', 'G♭, B♭♭, D♭', '/static/Fsharpm.png'),
       ('Gbm7', 'G♭, B, D♭, F♭', '/static/Fsharpm7.png'),
       ('Gbmaj7', 'G♭, B♭, D♭, F', '/static/Fsharpmaj7.png'),
       ('Gbsus4', 'G♭, B♭, E♭', '/static/Fsharpsus4.png'),
       ('F', 'F, A, C', '/static/F.png'),
       ('F5', 'F, C, F', '/static/F5.png'),
       ('F7', 'F, A, C, E♭', '/static/F7.png'),
       ('Fadd9', 'F, A, C, G', '/static/Fadd9.png'),
       ('Fdim', 'F, A♭, C♭', '/static/Fdim.png'),
       ('Fdim7', 'F, A♭, C♭, E♭♭', '/static/Fdim7.png'),
       ('Fm', 'F, A♭, C', '/static/Fm.png'),
       ('Fmin7', 'F, A♭, C, E♭', '/static/Fmin7.png'),
       ('Fmaj7', 'F, A, C, E', '/static/Fmaj7.png'),
       ('Fsus4', 'F, B♭, C', '/static/Fsus4.png'),
       ('G#', 'G#, B#, D#', '/static/Gsharp.png'),
       ('G#5', 'G#, D#, G#', '/static/Gsharp5.png'),
       ('G#7', 'G#, B#, D#, F#', '/static/Gsharp7.png'),
       ('G#add9', 'G#, B#, D#, A#', '/static/Gsharpadd9.png'),
       ('G#dim', 'G#, B, D', '/static/Gsharpdim.png'),
       ('G#dim7', 'G#, B, D, F', '/static/Gsharpdim7.png'),
       ('G#m', 'G#, B, D#', '/static/Gsharpm.png'),
       ('G#♭m7', 'G#, B, D#, F#', '/static/Gsharpm7.png'),
       ('G#maj7', 'G#, B#, D#, FX', '/static/Gsharpmaj7.png'),
       ('G#sus4', 'G#, C#, D#', '/static/Gsharpsus4.png'),
       ('Ab', 'A♭, C, E♭', '/static/Gsharp.png'),
       ('Ab5', 'A♭, E♭, A♭', '/static/Gsharp5.png'),
       ('Ab7', 'A♭, C, E♭, G♭', '/static/Gsharp7.png'),
       ('Abadd9', 'A♭, C, E♭, B♭', '/static/Gsharpadd9.png'),
       ('Abdim', 'A♭, C♭, E♭♭', '/static/Gsharpdim.png'),
       ('Abdim7', 'A♭, C♭, E♭♭, G♭♭', '/static/Gsharpdim7.png'),
       ('Abm', 'A♭, C♭, E♭', '/static/Gsharpm.png'),
       ('Abm7', 'A♭, C♭, E♭, G♭', '/static/Gsharpm7.png'),
       ('Abmaj7', 'A♭, C, E♭, G', '/static/Gsharpmaj7.png'),
       ('Absus4', 'A♭, D♭, E♭', '/static/Gsharpsus4.png'),
       ('G', 'G, B, D', '/static/G.png'),
       ('G5', 'G, D, G', '/static/G5.png'),
       ('G7', 'G, B, D, F', '/static/G7.png'),
       ('Gadd9', 'G, B, D, A', '/static/Gadd9.png'),
       ('Gdim', 'G, B♭, D♭', '/static/Gdim.png'),
       ('Gdim7', 'G, B♭, D♭, F♭', '/static/Gdim7.png'),
       ('Gm', 'G, B♭, D', '/static/Gm.png'),
       ('Gm7', 'G, B♭, D, F', '/static/Gm7.png'),
       ('Gmaj7', 'G, B, D, F#', '/static/Gmaj7.png'),
       ('Gsus4', 'G, C, D', '/static/Gsus4.png')